# === Range and Area Constants ===
MIN_DAB_STD_FOR_VALID_IMAGE = 14
MIN_CORE_AREA = 75
MAX_CORE_AREA = 3000
MIN_DAB_AREA = MIN_CORE_AREA
MAX_DAB_AREA = 25000
CORE_CIRCLE_RADIUS_MASK = 350

# === Remove Condition Constants ===
MIN_AVG_CORE_DAB_COLOR = 170
MIN_CORE_BODY_DIFF = 5
MIN_ARMS_LENGTH = 3
MAX_ARM_LENGTH_FOR_VALID = 556

# ***************** v1 ********************

USE_FFT = False

CORE_HEM_MEDIAN_APPROX_FACTOR = 1.8
CORE_SECONDARY_THRESHOLD = 101
CORE_SECONDARY_THRESHOLD_PERCENT = 0.3
CORE_SECONDARY_THRESHOLD_KERNEL_SIZE = 0

# ***************** v2 ********************

#USE_FFT = True
# CORE_HEM_MEDIAN_APPROX_FACTOR = 1.8
# CORE_SECONDARY_THRESHOLD = 101
# CORE_SECONDARY_THRESHOLD_PERCENT = 0.3
# CORE_SECONDARY_THRESHOLD_KERNEL_SIZE = 2

